Fixed compilation errors due to to many Win32 definitions.
git-svn-id: https://www.h3d.org:8090/H3DAPI/trunk/H3DAPI@492 610dfd11-2700-0410-9b68-9ae28eac5983