Fixed compilation error on Linux. xwConfigBase::Read takes a double*, cannot convert from float*
git-svn-id: https://www.h3d.org:8090/H3DAPI/trunk/H3DAPI@2040 610dfd11-2700-0410-9b68-9ae28eac5983